export const contextMessages = {
  en: {
    eyebrow: 'Built around you', library: 'Your exercise library', exercise: 'Exercise details', context: 'Your training context', memory: 'Remembered fact', backLibrary: 'Back to library', backExercise: 'Back to exercise', backContext: 'Back to training context', backMemory: 'Back to remembered fact',
    search: 'Search exercises', browse: 'Search', all: 'All exercises', favorites: 'Favorites', custom: 'Custom exercises', hidden: 'Hidden exercises', anyModality: 'All training types', resistance: 'Resistance', cardio: 'Cardio', mobility: 'Mobility', empty: 'No matching records.', page: 'Page {page} · {total} records', previous: 'Previous page', next: 'Next page',
    view: 'View details', customBadge: 'Your custom exercise', catalogBadge: 'Exercise library', archived: 'Archived', favorite: 'Add to favorites', unfavorite: 'Remove from favorites', hide: 'Hide from future searches', unhide: 'Show in future searches', history: 'View exercise progress', equipment: 'Equipment', equipmentContext: 'View my equipment', instructions: 'How to perform it', setup: 'Setup', cues: 'Form cues', mistakes: 'Common mistakes', breathing: 'Breathing', safety: 'Safety notes', contraindications: 'Considerations', tracking: 'What you can record',
    weight: 'Weight', reps: 'Repetitions', time: 'Time', distance: 'Distance', hr: 'Heart rate', pace: 'Pace', cadence: 'Cadence', power: 'Power', elevation: 'Elevation',
    height: 'Height', body: 'Recorded body context', targetWeight: 'Target weight', profile: 'Training profile', health: 'Health constraints', spaces: 'Training spaces', preferences: 'Preferences', memories: 'Remembered facts', goals: 'Training goals', interests: 'Training interests', focus: 'Focus areas', experience: 'Experience', novice: 'Beginner', intermediate: 'Intermediate', advanced: 'Advanced', days: 'Sessions per week', availableDays: 'Available days', anyDay: 'Any day', minutes: 'Time per session', motivation: 'Motivation', preparation: 'Sport or event context', preferredName: 'Preferred name', missing: 'Not recorded', limitations: 'Areas to train around', healthNotes: 'Your notes', noLimitations: 'No limitations recorded',
    defaultSpace: 'Default space', makeDefault: 'Make default', unconfigured: 'Equipment not configured — availability is unknown.', emptyInventory: 'Confirmed inventory: no equipment selected.', noEquipment: 'No custom equipment recorded.', notes: 'Notes', units: 'Display units', metric: 'Metric', imperial: 'Imperial', theme: 'Theme', system: 'Follow device', light: 'Light', dark: 'Dark', language: 'Language', weekStart: 'Week starts', sunday: 'Sunday', monday: 'Monday', skin: 'Theme style', calm: 'Editorial Calm', cyanotype: 'Cyanotype', camellia: 'Camellia',
    memoryHint: 'Your recorded facts, with their authorship. Measurements have their own dated history.', author: 'Recorded by', external: 'External AI client', user: 'You', ai: 'Built-in Coach', created: 'Created', updated: 'Last changed', editFact: 'Correct this fact', saveFact: 'Save correction', draft: 'Unsaved correction', memoryLimit: 'Use at most 500 characters. Exact measurements belong in body history.',
    askEdit: 'Ask my AI to edit', askCreate: 'Ask my AI to add', followUp: 'Help me update my eFitware {kind} ({id}). Ask which changes I want, use the existing records and canonical tools, then display the saved result. This request is not a saved change.', addFollowUp: 'Help me add to my eFitware {kind}. Use existing equipment and exercises before creating duplicates; ask for the details needed and display the saved result.',
    upper_body: 'Upper body', lower_body: 'Lower body', core: 'Core', back_posture: 'Back and posture', glutes: 'Glutes', arms: 'Arms', shoulders: 'Shoulders', conditioning: 'Conditioning', MO: 'Monday', TU: 'Tuesday', WE: 'Wednesday', TH: 'Thursday', FR: 'Friday', SA: 'Saturday', SU: 'Sunday'
  },
  de: {
    eyebrow: 'Auf dich abgestimmt', library: 'Deine Übungsbibliothek', exercise: 'Übungsdetails', context: 'Dein Trainingskontext', memory: 'Gemerkte Information', backLibrary: 'Zurück zur Bibliothek', backExercise: 'Zurück zur Übung', backContext: 'Zurück zum Trainingskontext', backMemory: 'Zurück zur Information',
    search: 'Übungen suchen', browse: 'Suchen', all: 'Alle Übungen', favorites: 'Favoriten', custom: 'Eigene Übungen', hidden: 'Ausgeblendete Übungen', anyModality: 'Alle Trainingsarten', resistance: 'Krafttraining', cardio: 'Ausdauer', mobility: 'Mobilität', empty: 'Keine passenden Einträge.', page: 'Seite {page} · {total} Einträge', previous: 'Vorherige Seite', next: 'Nächste Seite',
    view: 'Details ansehen', customBadge: 'Deine eigene Übung', catalogBadge: 'Übungsbibliothek', archived: 'Archiviert', favorite: 'Zu Favoriten hinzufügen', unfavorite: 'Aus Favoriten entfernen', hide: 'In künftigen Suchen ausblenden', unhide: 'In künftigen Suchen anzeigen', history: 'Übungsfortschritt ansehen', equipment: 'Ausrüstung', equipmentContext: 'Meine Ausrüstung ansehen', instructions: 'Ausführung', setup: 'Aufbau', cues: 'Technikhinweise', mistakes: 'Häufige Fehler', breathing: 'Atmung', safety: 'Sicherheitshinweise', contraindications: 'Zu beachten', tracking: 'Was du erfassen kannst',
    weight: 'Gewicht', reps: 'Wiederholungen', time: 'Zeit', distance: 'Distanz', hr: 'Herzfrequenz', pace: 'Tempo', cadence: 'Trittfrequenz', power: 'Leistung', elevation: 'Höhenmeter',
    height: 'Körpergröße', body: 'Erfasster Körperkontext', targetWeight: 'Zielgewicht', profile: 'Trainingsprofil', health: 'Gesundheitliche Einschränkungen', spaces: 'Trainingsorte', preferences: 'Einstellungen', memories: 'Gemerkte Informationen', goals: 'Trainingsziele', interests: 'Trainingsinteressen', focus: 'Schwerpunkte', experience: 'Erfahrung', novice: 'Einsteiger', intermediate: 'Fortgeschritten', advanced: 'Erfahren', days: 'Einheiten pro Woche', availableDays: 'Verfügbare Tage', anyDay: 'Jeder Tag', minutes: 'Zeit pro Einheit', motivation: 'Motivation', preparation: 'Sport- oder Wettkampfkontext', preferredName: 'Bevorzugter Name', missing: 'Nicht erfasst', limitations: 'Zu berücksichtigende Bereiche', healthNotes: 'Deine Notizen', noLimitations: 'Keine Einschränkungen erfasst',
    defaultSpace: 'Standardort', makeDefault: 'Als Standard wählen', unconfigured: 'Ausrüstung nicht konfiguriert — Verfügbarkeit unbekannt.', emptyInventory: 'Bestätigtes Inventar: keine Ausrüstung ausgewählt.', noEquipment: 'Keine eigene Ausrüstung erfasst.', notes: 'Notizen', units: 'Anzeigeeinheiten', metric: 'Metrisch', imperial: 'Imperial', theme: 'Design', system: 'Geräteeinstellung', light: 'Hell', dark: 'Dunkel', language: 'Sprache', weekStart: 'Wochenbeginn', sunday: 'Sonntag', monday: 'Montag', skin: 'Designstil', calm: 'Editorial Calm', cyanotype: 'Cyanotype', camellia: 'Camellia',
    memoryHint: 'Deine erfassten Fakten mit Urheberschaft. Messwerte haben einen eigenen datierten Verlauf.', author: 'Erfasst von', external: 'Externer KI-Client', user: 'Du', ai: 'Integrierter Coach', created: 'Erstellt', updated: 'Zuletzt geändert', editFact: 'Diese Information korrigieren', saveFact: 'Korrektur speichern', draft: 'Ungespeicherte Korrektur', memoryLimit: 'Höchstens 500 Zeichen. Genaue Messwerte gehören in den Körperverlauf.',
    askEdit: 'Meine KI um Änderungen bitten', askCreate: 'Meine KI um Ergänzungen bitten', followUp: 'Hilf mir, meinen eFitware-Bereich {kind} ({id}) zu bearbeiten. Frage nach den gewünschten Änderungen, nutze vorhandene Datensätze und kanonische Tools und zeige anschließend das gespeicherte Ergebnis. Diese Anfrage ist keine gespeicherte Änderung.', addFollowUp: 'Hilf mir, meinen eFitware-Bereich {kind} zu ergänzen. Nutze vorhandene Ausrüstung und Übungen, bevor du Duplikate erstellst; frage nach notwendigen Angaben und zeige das gespeicherte Ergebnis.',
    upper_body: 'Oberkörper', lower_body: 'Unterkörper', core: 'Rumpf', back_posture: 'Rücken und Haltung', glutes: 'Gesäß', arms: 'Arme', shoulders: 'Schultern', conditioning: 'Kondition', MO: 'Montag', TU: 'Dienstag', WE: 'Mittwoch', TH: 'Donnerstag', FR: 'Freitag', SA: 'Samstag', SU: 'Sonntag'
  }
}
