export const goalMessages = {
  en: {
    trainingGoal: 'Training goal', goalTarget: 'Target', targetDate: 'Target date', nextCheckIn: 'Next check-in', checkIns: 'Check-ins', viewGoalPlan: 'View goal plan', viewGoal: 'View goal', backToGoal: 'Back to goal', backToGoalPlan: 'Back to goal plan',
    goalStatus: { active: 'Active', achieved: 'Achieved', abandoned: 'Abandoned' }, setGoalStatus: { active: 'Reactivate goal', achieved: 'Mark goal achieved', abandoned: 'Abandon goal' },
    recordCheckIn: 'Record a check-in', checkInEvidenceNote: 'Record what you observed. A check-in does not mark this goal achieved.', checkInDate: 'Check-in date', checkInValue: 'Measured value (optional)', checkInNote: 'Your observations (optional)', saveCheckIn: 'Save check-in', discardCheckIn: 'Discard entry', finishCheckIn: 'Save or discard this entry before navigating or changing the goal.', checkInHistory: 'Check-in history', manageGoal: 'Goal status', goalStatusNote: 'Choose the status yourself. Your recorded evidence and training history stay available.',
    goalAdaptPrompt: 'Help me adjust my saved eFitware goal {id} or design its plan. Read the goal and current plan, clarify the changes I want, then save only the agreed changes and display the result.',
    goalPlan: 'Goal plan', planStatus: { active: 'Active', paused: 'Paused', completed: 'Completed', archived: 'Archived' }, setPlanStatus: { active: 'Activate plan', paused: 'Pause plan', completed: 'Mark plan completed', archived: 'Archive plan' },
    manualManagement: 'Managed with your own AI', coachManagement: 'Managed by eFitware Coach', coachPaused: 'Automatic Coach reviews are paused while in-app AI is disabled.', planVersion: 'Version {number}', activeVersion: 'Active version', historicalVersion: 'Viewing a historical version', externalAuthorship: 'Authored with an external AI connection', coachAuthorship: 'Authored by eFitware Coach', userAuthorship: 'Authored by you',
    feasibility: { reasonable: 'Assessed as reasonable', ambitious: 'Assessed as ambitious', not_credible: 'Assessed as not credible', insufficient_data: 'Not enough evidence to assess' }, feasibilityNote: 'This is the plan author’s assessment, not a guarantee or a measurement of achievement.',
    viewActiveVersion: 'View active version', activateVersion: 'Make this the active version', activationNote: 'Activating changes the plan version. Existing workouts and completed history stay unchanged.', planPhases: 'Your training phases', phaseDatesNote: 'Phase labels describe their dates. They do not claim that training or milestones have been completed.', phaseNumber: 'Phase {number}', phasePast: 'Past dates', phaseFuture: 'Upcoming', phaseCurrent: 'Current dates', plannedReview: 'Planned review:', milestones: 'Milestones', removedProgram: 'The program linked to this phase is no longer available.', versionHistory: 'Changes and history',
    revisionEvidence: 'Upcoming sessions updated: {replaced}. User-edited sessions kept: {skipped}.', unchangedReviews: 'Coach reviews with no plan change', reviewEvidence: 'Completed sessions: {sessions}; linked to this goal: {goals}; personal records: {prs}; check-ins: {checkIns}; other commitments: {commitments}.',
    managePlan: 'Manage this plan', planStatusNote: 'Plan status is separate from goal achievement. These actions keep workouts and history.', coachManagementNote: 'This plan is managed by eFitware Coach. Ask your AI about changes; taking over management requires your explicit agreement.',
    planAdaptPrompt: 'Help me revise my eFitware goal plan {id}. Read the current goal, plan and evidence. Ask what I want changed. If Coach manages it, obtain my explicit agreement before taking over. Publish only agreed changes and display the saved plan.'
  },
  de: {
    trainingGoal: 'Trainingsziel', goalTarget: 'Zielwert', targetDate: 'Zieldatum', nextCheckIn: 'Nächster Check-in', checkIns: 'Check-ins', viewGoalPlan: 'Zielplan ansehen', viewGoal: 'Ziel ansehen', backToGoal: 'Zurück zum Ziel', backToGoalPlan: 'Zurück zum Zielplan',
    goalStatus: { active: 'Aktiv', achieved: 'Erreicht', abandoned: 'Aufgegeben' }, setGoalStatus: { active: 'Ziel reaktivieren', achieved: 'Ziel als erreicht markieren', abandoned: 'Ziel aufgeben' },
    recordCheckIn: 'Check-in erfassen', checkInEvidenceNote: 'Halte deine Beobachtungen fest. Ein Check-in markiert das Ziel nicht als erreicht.', checkInDate: 'Check-in-Datum', checkInValue: 'Messwert (optional)', checkInNote: 'Deine Beobachtungen (optional)', saveCheckIn: 'Check-in speichern', discardCheckIn: 'Eintrag verwerfen', finishCheckIn: 'Speichere oder verwirf diesen Eintrag, bevor du navigierst oder das Ziel änderst.', checkInHistory: 'Check-in-Verlauf', manageGoal: 'Zielstatus', goalStatusNote: 'Du wählst den Status selbst. Deine Beobachtungen und dein Trainingsverlauf bleiben erhalten.',
    goalAdaptPrompt: 'Hilf mir, mein gespeichertes eFitware-Ziel {id} anzupassen oder seinen Plan zu erstellen. Lies das Ziel und den aktuellen Plan, kläre meine gewünschten Änderungen und speichere nur die vereinbarten Änderungen. Zeige anschließend das Ergebnis.',
    goalPlan: 'Zielplan', planStatus: { active: 'Aktiv', paused: 'Pausiert', completed: 'Abgeschlossen', archived: 'Archiviert' }, setPlanStatus: { active: 'Plan aktivieren', paused: 'Plan pausieren', completed: 'Plan als abgeschlossen markieren', archived: 'Plan archivieren' },
    manualManagement: 'Mit deiner eigenen KI verwaltet', coachManagement: 'Von eFitware Coach verwaltet', coachPaused: 'Automatische Coach-Prüfungen sind pausiert, solange die KI in der App deaktiviert ist.', planVersion: 'Version {number}', activeVersion: 'Aktive Version', historicalVersion: 'Historische Version wird angezeigt', externalAuthorship: 'Mit einer externen KI-Verbindung erstellt', coachAuthorship: 'Von eFitware Coach erstellt', userAuthorship: 'Von dir erstellt',
    feasibility: { reasonable: 'Als realistisch eingeschätzt', ambitious: 'Als ambitioniert eingeschätzt', not_credible: 'Als nicht plausibel eingeschätzt', insufficient_data: 'Nicht genügend Daten zur Einschätzung' }, feasibilityNote: 'Dies ist die Einschätzung des Planverfassers, keine Garantie oder Messung der Zielerreichung.',
    viewActiveVersion: 'Aktive Version ansehen', activateVersion: 'Diese Version aktivieren', activationNote: 'Die Aktivierung ändert die Planversion. Bestehende Trainings und der abgeschlossene Verlauf bleiben unverändert.', planPhases: 'Deine Trainingsphasen', phaseDatesNote: 'Phasenbezeichnungen beschreiben Zeiträume. Sie sagen nicht aus, dass Trainings oder Meilensteine abgeschlossen sind.', phaseNumber: 'Phase {number}', phasePast: 'Vergangener Zeitraum', phaseFuture: 'Bevorstehend', phaseCurrent: 'Aktueller Zeitraum', plannedReview: 'Geplante Prüfung:', milestones: 'Meilensteine', removedProgram: 'Das mit dieser Phase verknüpfte Programm ist nicht mehr verfügbar.', versionHistory: 'Änderungen und Verlauf',
    revisionEvidence: 'Aktualisierte bevorstehende Einheiten: {replaced}. Beibehaltene, von dir bearbeitete Einheiten: {skipped}.', unchangedReviews: 'Coach-Prüfungen ohne Planänderung', reviewEvidence: 'Abgeschlossene Einheiten: {sessions}; diesem Ziel zugeordnet: {goals}; persönliche Rekorde: {prs}; Check-ins: {checkIns}; weitere Verpflichtungen: {commitments}.',
    managePlan: 'Plan verwalten', planStatusNote: 'Planstatus und Zielerreichung sind unabhängig. Trainings und Verlauf bleiben bei diesen Aktionen erhalten.', coachManagementNote: 'Dieser Plan wird von eFitware Coach verwaltet. Besprich Änderungen mit deiner KI. Die Übernahme der Verwaltung erfordert deine ausdrückliche Zustimmung.',
    planAdaptPrompt: 'Hilf mir, meinen eFitware-Zielplan {id} zu überarbeiten. Lies das aktuelle Ziel, den Plan und die Beobachtungen. Frage nach meinen gewünschten Änderungen. Falls Coach den Plan verwaltet, hole vor der Übernahme meine ausdrückliche Zustimmung ein. Veröffentliche nur vereinbarte Änderungen und zeige den gespeicherten Plan.'
  }
}
