export const outcomeMessages = {
  en: {
    actions: {"add_workout_activity": "Added workout activity", "add_workout_exercise": "Added workout exercise", "add_workout_set": "Added set", "create_custom_equipment": "Created equipment", "create_custom_exercise": "Created custom exercise", "create_goal": "Created goal", "create_goal_check_in": "Created goal observation", "create_memory": "Created remembered fact", "create_program": "Created program", "create_schedule": "Created schedule", "create_template": "Created template", "create_training_space": "Created training space", "create_workout": "Created workout", "delete_body_metric": "Removed body measurement", "delete_custom_equipment": "Removed equipment", "delete_custom_exercise": "Removed custom exercise", "delete_goal": "Removed goal", "delete_goal_check_in": "Removed goal observation", "delete_memory": "Removed remembered fact", "delete_program": "Removed program", "delete_schedule": "Removed schedule", "delete_template": "Removed template", "delete_training_space": "Removed training space", "delete_workout": "Removed workout", "delete_workout_activity": "Removed workout activity", "delete_workout_commentary": "Removed external commentary", "delete_workout_exercise": "Removed workout exercise", "delete_workout_set": "Removed set", "set_workout_commentary": "Saved external commentary", "update_custom_equipment": "Updated equipment", "update_custom_exercise": "Updated custom exercise", "update_exercise_preferences": "Updated exercise preferences", "update_goal": "Updated goal", "update_health": "Updated health context", "update_memory": "Updated remembered fact", "update_preferences": "Updated preferences", "update_program": "Updated program", "update_schedule": "Updated schedule", "update_template": "Updated template", "update_training_space": "Updated training space", "update_user_profile": "Updated training profile", "update_workout": "Updated workout", "update_workout_activity": "Updated workout activity", "update_workout_exercise": "Updated workout exercise", "activate_goal_plan_version": "Activated plan version", "publish_goal_plan": "Published goal plan", "record_body_metric": "Recorded body measurement", "reorder_workout": "Reordered workout", "save_week_plan": "Saved training week", "set_goal_plan_status": "Changed goal-plan status", "start_workout": "Started workout", "undo_action": "Undid saved change", "log_set": "Recorded set results", "log_sets": "Recorded set results"},
    capability: { weight_kg: 'Weight', body_fat_percent: 'Body fat', resting_heart_rate_bpm: 'Resting heart rate', heart_rate_variability_ms: 'Heart-rate variability', steps: 'Steps', sleep_session: 'Sleep', workouts: 'Workouts' },
    chartData: 'Chart values', observations: 'Observation {index}', weekSummary: 'Week {index}: {count} recorded training days',

    undoConflict: 'This change cannot be undone because its records changed again. Reload the saved records before deciding what to change.', status: 'Your account status', account: 'Account', integrations: 'Connections', exports: 'Export status', onboarding: 'Account setup', consent: 'Health-data consent', complete: 'Complete', incomplete: 'Not complete', accepted: 'Accepted', missing: 'Not accepted', appSettings: 'Open app settings', finishSetup: 'Finish setup in the app', metadataOnly: 'Recorded connection history. This view cannot connect a provider or start a sync.', exportOnly: 'Only unexpired export status is shown. Create and download account archives in app settings.', empty: 'No records to show.', created: 'Created', updated: 'Last changed', expires: 'Expires', ready: 'Ready',
    integration: 'Connection history', lastSync: 'Last successful sync', never: 'Not recorded', capabilities: 'Recorded capabilities', error: 'Last issue', noError: 'None recorded', syncHistory: 'Recorded sync runs', received: 'Received', unchanged: 'Unchanged', applied: 'Applied', review: 'Needs review', invalid: 'Invalid', started: 'Started', finished: 'Finished', errors: 'Reported issues', recordIndex: 'Record {index}',
    connecting: 'Connecting', connected: 'Connected', permission_limited: 'Limited permissions', attention_required: 'Needs attention', disconnected: 'Disconnected', running: 'Running', completed: 'Completed', failed: 'Failed',
    health_connect: 'Health Connect', healthkit: 'Apple Health', withings: 'Withings', strava: 'Strava', strong_csv: 'Strong CSV', fit_file: 'FIT file', tcx_file: 'TCX file',
    provider_unavailable: 'Provider unavailable', authorization_required: 'Authorization required', invalid_record: 'Invalid record', reconciliation_failed: 'Reconciliation failed', connection_changed: 'Connection changed', limit_reached: 'Limit reached',
    receipts: 'Your saved changes', receiptHint: 'Retained external AI changes, usually about 30 days. Undo can be refused if records changed again.', undo: 'Undo this change', undone: 'Undone', cannotUndo: 'Undo unavailable', confirmUndo: 'Undo this saved change?', cancel: 'Cancel', confirm: 'Confirm undo', viewRecord: 'View related record', lastReceipt: 'View change receipts', externalChange: 'External AI change',
    workoutReview: 'Workout review', coachReflection: 'Built-in Coach reflection', externalCommentary: 'External AI commentary', noReflection: 'No commentary recorded.', decisionHistory: 'Built-in Coach history', factors: 'Recorded factors', changes: 'Recorded changes', limitations: 'Limitations', current: 'Current', historical: 'Historical', partially_undone: 'Partially undone', editCommentary: 'Edit external commentary', saveCommentary: 'Save commentary', deleteCommentary: 'Remove external commentary', confirmDeleteCommentary: 'Remove only this external commentary?', confirmRemove: 'Confirm removal', commentaryDraft: 'Unsaved commentary', askReview: 'Ask my AI to review', reviewRequest: 'Review my completed eFitware workout {id}, using its actual recorded results. Explain the evidence and limitations. If I ask to save commentary, use set_workout_commentary with the existing revision; keep built-in Coach history separate and open_workout_review afterward.',
    startWorkout: 'Start this workout', completeWorkout: 'Mark workout complete', completeHint: 'Complete the session? Unchecked sets remain unchecked.', confirmComplete: 'Complete session', savedReview: 'View commentary and history', editWorkout: 'Ask my AI to adjust', editWorkoutRequest: 'Help me adjust my eFitware workout {id}. Ask which changes I want, preserve recorded actuals and use canonical tools with revisions. Then open_workout to display the saved result.',
    share: 'Share preview', previewOnly: 'Private preview. Nothing has been posted or sent.', chartPreview: 'Bounded chart preview from the recorded source.', caption: 'Caption', copyCaption: 'Copy caption', copied: 'Caption copied', copyFailed: 'Copy unavailable; select the caption text below.', options: 'Include in this preview', includeFirstName: 'First name', includeWorkoutName: 'Workout name', includeExerciseName: 'Exercise name', includeDate: 'Date', prepareShare: 'Prepare share preview',
    backStatus: 'Back to status', backIntegration: 'Back to connection', backReceipts: 'Back to changes', backReview: 'Back to workout review', backShare: 'Back to share preview'
  },
  de: {
    actions: {"add_workout_activity": "Hinzugefügt: Trainingsaktivität", "add_workout_exercise": "Hinzugefügt: Trainingsübung", "add_workout_set": "Hinzugefügt: Satz", "create_custom_equipment": "Erstellt: Gerät", "create_custom_exercise": "Erstellt: eigene Übung", "create_goal": "Erstellt: Ziel", "create_goal_check_in": "Erstellt: Zielbeobachtung", "create_memory": "Erstellt: gemerkte Angabe", "create_program": "Erstellt: Programm", "create_schedule": "Erstellt: Trainingsplan", "create_template": "Erstellt: Vorlage", "create_training_space": "Erstellt: Trainingsort", "create_workout": "Erstellt: Training", "delete_body_metric": "Entfernt: Körpermesswert", "delete_custom_equipment": "Entfernt: Gerät", "delete_custom_exercise": "Entfernt: eigene Übung", "delete_goal": "Entfernt: Ziel", "delete_goal_check_in": "Entfernt: Zielbeobachtung", "delete_memory": "Entfernt: gemerkte Angabe", "delete_program": "Entfernt: Programm", "delete_schedule": "Entfernt: Trainingsplan", "delete_template": "Entfernt: Vorlage", "delete_training_space": "Entfernt: Trainingsort", "delete_workout": "Entfernt: Training", "delete_workout_activity": "Entfernt: Trainingsaktivität", "delete_workout_commentary": "Entfernt: externer Kommentar", "delete_workout_exercise": "Entfernt: Trainingsübung", "delete_workout_set": "Entfernt: Satz", "set_workout_commentary": "Gespeichert: externer Kommentar", "update_custom_equipment": "Geändert: Gerät", "update_custom_exercise": "Geändert: eigene Übung", "update_exercise_preferences": "Geändert: Übungseinstellungen", "update_goal": "Geändert: Ziel", "update_health": "Geändert: Gesundheitsangaben", "update_memory": "Geändert: gemerkte Angabe", "update_preferences": "Geändert: Einstellungen", "update_program": "Geändert: Programm", "update_schedule": "Geändert: Trainingsplan", "update_template": "Geändert: Vorlage", "update_training_space": "Geändert: Trainingsort", "update_user_profile": "Geändert: Trainingsprofil", "update_workout": "Geändert: Training", "update_workout_activity": "Geändert: Trainingsaktivität", "update_workout_exercise": "Geändert: Trainingsübung", "activate_goal_plan_version": "Planversion aktiviert", "publish_goal_plan": "Zielplan veröffentlicht", "record_body_metric": "Körpermesswert erfasst", "reorder_workout": "Training neu geordnet", "save_week_plan": "Trainingswoche gespeichert", "set_goal_plan_status": "Zielplanstatus geändert", "start_workout": "Training gestartet", "undo_action": "Änderung rückgängig gemacht", "log_set": "Satzergebnisse erfasst", "log_sets": "Satzergebnisse erfasst"},
    capability: { weight_kg: 'Gewicht', body_fat_percent: 'Körperfett', resting_heart_rate_bpm: 'Ruhepuls', heart_rate_variability_ms: 'Herzfrequenzvariabilität', steps: 'Schritte', sleep_session: 'Schlaf', workouts: 'Trainings' },
    chartData: 'Diagrammwerte', observations: 'Messpunkt {index}', weekSummary: 'Woche {index}: {count} erfasste Trainingstage',

    undoConflict: 'Diese Änderung kann nicht rückgängig gemacht werden, weil die Einträge erneut geändert wurden. Lade die gespeicherten Einträge neu, bevor du Änderungen festlegst.', status: 'Dein Kontostatus', account: 'Konto', integrations: 'Verbindungen', exports: 'Exportstatus', onboarding: 'Kontoeinrichtung', consent: 'Einwilligung für Gesundheitsdaten', complete: 'Abgeschlossen', incomplete: 'Nicht abgeschlossen', accepted: 'Erteilt', missing: 'Nicht erteilt', appSettings: 'App-Einstellungen öffnen', finishSetup: 'Einrichtung in der App abschließen', metadataOnly: 'Gespeicherter Verbindungsverlauf. Diese Ansicht kann keinen Anbieter verbinden oder eine Synchronisierung starten.', exportOnly: 'Nur nicht abgelaufene Exportstatus werden angezeigt. Kontoarchive erstellst und lädst du in den App-Einstellungen.', empty: 'Keine Einträge vorhanden.', created: 'Erstellt', updated: 'Zuletzt geändert', expires: 'Läuft ab', ready: 'Bereit',
    integration: 'Verbindungsverlauf', lastSync: 'Letzte erfolgreiche Synchronisierung', never: 'Nicht erfasst', capabilities: 'Erfasste Berechtigungen', error: 'Letztes Problem', noError: 'Keines erfasst', syncHistory: 'Gespeicherte Synchronisierungen', received: 'Empfangen', unchanged: 'Unverändert', applied: 'Übernommen', review: 'Zu prüfen', invalid: 'Ungültig', started: 'Gestartet', finished: 'Beendet', errors: 'Gemeldete Probleme', recordIndex: 'Datensatz {index}',
    connecting: 'Wird verbunden', connected: 'Verbunden', permission_limited: 'Eingeschränkte Berechtigungen', attention_required: 'Handlungsbedarf', disconnected: 'Getrennt', running: 'Läuft', completed: 'Abgeschlossen', failed: 'Fehlgeschlagen',
    health_connect: 'Health Connect', healthkit: 'Apple Health', withings: 'Withings', strava: 'Strava', strong_csv: 'Strong CSV', fit_file: 'FIT-Datei', tcx_file: 'TCX-Datei',
    provider_unavailable: 'Anbieter nicht verfügbar', authorization_required: 'Autorisierung erforderlich', invalid_record: 'Ungültiger Datensatz', reconciliation_failed: 'Abgleich fehlgeschlagen', connection_changed: 'Verbindung geändert', limit_reached: 'Limit erreicht',
    receipts: 'Deine gespeicherten Änderungen', receiptHint: 'Aufbewahrte Änderungen externer KI, meist etwa 30 Tage. Rückgängig kann bei späteren Änderungen abgelehnt werden.', undo: 'Änderung rückgängig machen', undone: 'Rückgängig gemacht', cannotUndo: 'Rückgängig nicht verfügbar', confirmUndo: 'Diese gespeicherte Änderung rückgängig machen?', cancel: 'Abbrechen', confirm: 'Rückgängig bestätigen', viewRecord: 'Verknüpften Eintrag ansehen', lastReceipt: 'Änderungsbelege ansehen', externalChange: 'Änderung durch externe KI',
    workoutReview: 'Trainingsrückblick', coachReflection: 'Rückblick des integrierten Coachs', externalCommentary: 'Kommentar externer KI', noReflection: 'Kein Kommentar erfasst.', decisionHistory: 'Verlauf des integrierten Coachs', factors: 'Erfasste Faktoren', changes: 'Erfasste Änderungen', limitations: 'Grenzen', current: 'Aktuell', historical: 'Historisch', partially_undone: 'Teilweise rückgängig', editCommentary: 'Externen Kommentar bearbeiten', saveCommentary: 'Kommentar speichern', deleteCommentary: 'Externen Kommentar entfernen', confirmDeleteCommentary: 'Nur diesen externen Kommentar entfernen?', confirmRemove: 'Entfernen bestätigen', commentaryDraft: 'Ungespeicherter Kommentar', askReview: 'Meine KI um einen Rückblick bitten', reviewRequest: 'Analysiere mein abgeschlossenes eFitware-Training {id} anhand der tatsächlich erfassten Ergebnisse. Erkläre Belege und Grenzen. Wenn ich einen gespeicherten Kommentar wünsche, nutze set_workout_commentary mit der vorhandenen Revision; halte den Coach-Verlauf getrennt und rufe anschließend open_workout_review auf.',
    startWorkout: 'Dieses Training starten', completeWorkout: 'Training als abgeschlossen markieren', completeHint: 'Einheit abschließen? Nicht abgehakte Sätze bleiben unverändert.', confirmComplete: 'Einheit abschließen', savedReview: 'Kommentar und Verlauf ansehen', editWorkout: 'Meine KI um Anpassungen bitten', editWorkoutRequest: 'Hilf mir, mein eFitware-Training {id} anzupassen. Frage nach den gewünschten Änderungen, erhalte tatsächliche Ergebnisse und nutze kanonische Tools mit Revisionen. Zeige danach das gespeicherte Ergebnis mit open_workout.',
    share: 'Teilungsvorschau', previewOnly: 'Private Vorschau. Nichts wurde veröffentlicht oder gesendet.', chartPreview: 'Begrenzte Diagrammvorschau aus der gespeicherten Quelle.', caption: 'Begleittext', copyCaption: 'Begleittext kopieren', copied: 'Begleittext kopiert', copyFailed: 'Kopieren nicht verfügbar; markiere den Text unten.', options: 'In dieser Vorschau anzeigen', includeFirstName: 'Vorname', includeWorkoutName: 'Trainingsname', includeExerciseName: 'Übungsname', includeDate: 'Datum', prepareShare: 'Teilungsvorschau vorbereiten',
    backStatus: 'Zurück zum Status', backIntegration: 'Zurück zur Verbindung', backReceipts: 'Zurück zu Änderungen', backReview: 'Zurück zum Trainingsrückblick', backShare: 'Zurück zur Teilungsvorschau'
  }
}
