import { z } from 'zod'
import { presentationSchema } from './model.ts'
const id = z.string().regex(/^[a-f0-9]{24}$/i)
const meta = z.object({ page: z.number().int().positive(), limit: z.number().int().positive(), total: z.number().int().nonnegative() })
const presentation = presentationSchema.extend({ timeZone: z.string() })
const connection = z.object({ id, provider: z.string(), transport: z.enum(['device', 'oauth', 'file']), status: z.enum(['connecting', 'connected', 'permission_limited', 'attention_required', 'disconnected']), grantedScopes: z.array(z.string()), capabilities: z.array(z.string()), createdAt: z.string(), updatedAt: z.string(), lastSuccessfulSyncAt: z.string().nullable(), lastErrorCode: z.string().nullable(), disconnectedAt: z.string().nullable() })
const run = z.object({ id, connectionId: id, trigger: z.enum(['initial', 'manual', 'webhook', 'reconcile']), status: z.enum(['running', 'completed', 'failed']), counts: z.object({ received: z.number(), unchanged: z.number(), applied: z.number(), review: z.number(), invalid: z.number() }), errors: z.array(z.object({ index: z.number(), code: z.string() })), startedAt: z.string(), completedAt: z.string().nullable() })
export const statusViewSchema = z.object({ view: z.literal('status'), record: z.object({ onboardingComplete: z.boolean(), healthDataConsentAccepted: z.boolean() }), related: z.object({ section: z.enum(['account', 'integrations', 'exports']), connections: z.object({ data: z.array(connection), meta }), exports: z.object({ data: z.array(z.object({ id, status: z.literal('ready'), createdAt: z.string(), expiresAt: z.string() })), meta }) }), presentation })
export const integrationViewSchema = z.object({ view: z.literal('integration'), record: connection, related: z.object({ runs: z.object({ data: z.array(run), meta }) }), presentation })
const entity = z.object({ type: z.string(), id: z.string().optional(), date: z.string().optional() })
export const receiptsViewSchema = z.object({ view: z.literal('receipts'), record: z.object({ data: z.array(z.object({ id, tool: z.string().optional(), summary: z.string().optional(), entities: z.array(entity), createdAt: z.string(), undoneAt: z.string().nullable(), undoable: z.boolean(), clientId: z.string().optional() })), meta }), related: z.object({}), presentation })
export const reviewViewSchema = z.object({ view: z.literal('workout-review'), record: z.object({ id, title: z.string(), date: z.string(), status: z.enum(['planned', 'in_progress', 'completed', 'skipped', 'abandoned']) }), related: z.object({ reflections: z.object({ workoutId: id, coach: z.object({ content: z.string(), generatedAt: z.string(), updatedAt: z.string().optional() }).nullable(), external: z.object({ content: z.string(), createdAt: z.string(), updatedAt: z.string(), externalMcp: z.object({ clientId: z.string() }) }).nullable(), revision: z.string().regex(/^commentary:1:[a-f0-9]{64}$/).nullable() }), decisions: z.object({ data: z.array(z.object({ id, headline: z.string(), explanation: z.string(), kind: z.string(), state: z.enum(['current', 'historical', 'partially_undone', 'undone']), source: z.string(), createdAt: z.string(), factors: z.array(z.object({ kind: z.string(), label: z.string(), detail: z.string().optional() })), changes: z.array(z.object({ summary: z.string(), exerciseId: z.string().optional() })), limitations: z.array(z.string()) })), meta }) }), presentation })
const option = z.enum(['includeFirstName', 'includeWorkoutName', 'includeExerciseName', 'includeDate'])
const shareRequest = z.object({ kind: z.enum(['personal_record', 'workout_complete', 'exercise_progress', 'training_progress', 'period_summary']), locale: z.enum(['en', 'de']), unitSystem: z.enum(['metric', 'imperial']), options: z.partialRecord(option, z.boolean()), workoutId: id.optional(), exerciseId: id.optional(), setId: z.string().optional(), range: z.enum(['4w', '8w', '12w', '1y']).optional(), today: z.string().optional(), metric: z.enum(['volume', 'consistency', 'training_time']).optional(), period: z.enum(['week', 'month', 'year']).optional(), through: z.string().optional() })
const chart = z.discriminatedUnion('type', [z.object({ type: z.literal('dots'), weeks: z.array(z.array(z.boolean())) }), z.object({ type: z.literal('bars'), bars: z.array(z.object({ label: z.string(), value: z.number() })) }), z.object({ type: z.literal('line'), points: z.array(z.number()), startLabel: z.string(), endLabel: z.string() })])
export const shareViewSchema = z.object({ view: z.literal('share'), record: z.object({ version: z.literal(2), kind: shareRequest.shape.kind, locale: z.enum(['en', 'de']), unitSystem: z.enum(['metric', 'imperial']), theme: z.enum(['light', 'dark']), eyebrow: z.string(), date: z.string().optional(), titleLines: z.array(z.string()), hero: z.object({ value: z.string(), unit: z.string().optional() }), subline: z.string().optional(), facts: z.array(z.object({ label: z.string(), value: z.string(), unit: z.string().optional() })), chart: chart.optional(), attribution: z.object({ brand: z.literal('eFitware'), domain: z.literal('efitware.com') }), caption: z.string(), landingUrl: z.string(), filename: z.string() }), related: z.object({ request: shareRequest, availableOptions: z.partialRecord(option, z.object({ enabled: z.boolean(), defaultValue: z.boolean() })) }), presentation })
export const outcomeViewSchema = z.discriminatedUnion('view', [statusViewSchema, integrationViewSchema, receiptsViewSchema, reviewViewSchema, shareViewSchema])
export type OutcomeView = z.infer<typeof outcomeViewSchema>
export type StatusView = z.infer<typeof statusViewSchema>
export type IntegrationView = z.infer<typeof integrationViewSchema>
export type ReceiptsView = z.infer<typeof receiptsViewSchema>
export type ReviewView = z.infer<typeof reviewViewSchema>
export type ShareView = z.infer<typeof shareViewSchema>
